/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#314d2e",
        "secondary": "#7a573b",
        "on-background": "#191d17",
        "on-error": "#ffffff",
        "secondary-container": "#fdceab",
        "primary-fixed-dim": "#aecfa6",
        "primary": "#183317",
        "outline-variant": "#c3c8be",
        "on-primary": "#ffffff",
        "on-surface-variant": "#434840",
        "on-tertiary-fixed": "#2a1700",
        "outline": "#737970",
        "surface-container-low": "#f2f5eb",
        "error": "#ba1a1a",
        "inverse-surface": "#2d322b",
        "surface-tint": "#486644",
        "on-secondary-container": "#79563a",
        "inverse-primary": "#aecfa6",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#653e00",
        "on-tertiary-container": "#e8a242",
        "primary-container": "#2e4a2b",
        "on-primary-container": "#99b991",
        "on-secondary-fixed": "#2d1602",
        "secondary-fixed": "#ffdcc3",
        "surface-container-highest": "#e0e4da",
        "on-error-container": "#93000a",
        "surface-container": "#ecefe5",
        "inverse-on-surface": "#eff2e8",
        "surface": "#f7fbf1",
        "tertiary-container": "#603b00",
        "tertiary-fixed": "#ffddb7",
        "background": "#f7fbf1",
        "surface-container-high": "#e6e9e0",
        "on-primary-fixed": "#062107",
        "surface-bright": "#f7fbf1",
        "surface-dim": "#d8dbd2",
        "on-secondary-fixed-variant": "#5f4026",
        "tertiary": "#422700",
        "secondary-fixed-dim": "#ebbe9b",
        "on-surface": "#191d17",
        "error-container": "#ffdad6",
        "surface-variant": "#e0e4da",
        "on-secondary": "#ffffff",
        "primary-fixed": "#caecc1",
        "tertiary-fixed-dim": "#ffb95e",
        "surface-container-lowest": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      fontFamily: {
        sans: ["Pretendard Variable", "Pretendard", "-apple-system", "BlinkMacSystemFont", "system-ui", "Roboto", "sans-serif"],
        "body-sm": ["Pretendard Variable", "Pretendard", "Manrope", "sans-serif"],
        "body-md": ["Pretendard Variable", "Pretendard", "Manrope", "sans-serif"],
        "body-lg": ["Pretendard Variable", "Pretendard", "Manrope", "sans-serif"],
        caption: ["Pretendard Variable", "Pretendard", "Manrope", "sans-serif"],
        "label-sm": ["Pretendard Variable", "Pretendard", "Manrope", "sans-serif"],
        "label-md": ["Pretendard Variable", "Pretendard", "Manrope", "sans-serif"],
        "headline-sm": ["Pretendard Variable", "Pretendard", "Space Grotesk", "sans-serif"],
        "headline-md": ["Pretendard Variable", "Pretendard", "Space Grotesk", "sans-serif"],
        "headline-lg": ["Pretendard Variable", "Pretendard", "Space Grotesk", "sans-serif"],
        "display-lg": ["Pretendard Variable", "Pretendard", "Space Grotesk", "sans-serif"],
        "display-metric": ["JetBrains Mono", "Pretendard Variable", "monospace"],
        "label-numeric": ["JetBrains Mono", "Pretendard Variable", "monospace"],
      },
      spacing: {
        "touch-lg": "3.5rem",
        "gap-compact": "0.5rem",
        "pad-card-x": "1.25rem",
        "gutter-grid": "0.75rem",
        "touch-min": "3rem",
        "gap-section": "1.5rem",
        "gap-default": "1rem",
        "pad-card-y": "1rem",
        "margin-screen": "1rem",
      },
    },
  },
  plugins: [],
}
